### ISSUE TITLE
Retrieved `null` from GitHub OAuth while No Public Email Address is Found

### ISSUE THREAD

**Issue by stanleyowen** [stanleyowen/otlio#247]
**Describe the bug**
Something went wrong with GitHub OAuth which cause the server to responds with 500 (Internal Server Error) error code.

**To Reproduce**
1. Click on GitHub OAuth
2. See error

**Expected behavior**
There shouldn't have any error in authenticating GitHub OAuth.

**Screenshots**
![Error in Authenticating GitHub OAuth](https://user-images.githubusercontent.com/69080584/127741291-da0233ed-faf4-40fd-b1be-01c96401de1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 OS Version 2009 (Build 19043.1110)
 - Browser Chrome
 - Version 92.0.4515.107

**Comment by stanleyowen** [comment]
```
Error: users validation failed: email: Path `email` is required.
    at ValidationError.inspect (E:\otlio\server\node_modules\mongoose\lib\error\validation.js:47:26)        
    at formatValue (internal/util/inspect.js:736:19)  
    at inspect (internal/util/inspect.js:310:10)      
    at formatWithOptionsInternal (internal/util/inspect.js:1969:40)
    at formatWithOptions (internal/util/inspect.js:1851:10)
    at console.value (internal/console/constructor.js:323:14)
    at console.log (internal/console/constructor.js:358:61)
    at E:\otlio\server\routes\oauth.route.js:15:17    
    at Strategy.strategy.error (E:\otlio\server\node_modules\passport\lib\middleware\authenticate.js:358:18)    at verified (E:\otlio\server\node_modules\passport-oauth2\lib\strategy.js:183:38)
    at E:\otlio\server\lib\passport.js:258:32
    at E:\otlio\server\node_modules\mongoose\lib\model.js:5074:18
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errors: {
    email: ValidatorError: Path `email` is required.  
        at validate (E:\otlio\server\node_modules\mongoose\lib\schematype.js:1270:13)
        at E:\otlio\server\node_modules\mongoose\lib\schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (E:\otlio\server\node_modules\mongoose\lib\schematype.js:1198:14)
        at E:\otlio\server\node_modules\mongoose\lib\document.js:2545:18
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'email',
      value: null,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'users validation failed'
} undefined undefined
```
It looks like the email retrieved from GitHub OAuth has a `null` value, this may be occurred when a users select to hide the public email address.

Details: https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

**Comment by stanleyowen** [comment]
Rather than using additional `axios` dependency for requesting data from GitHub server, we will try to upgrade `passport-github` Dependency to `passport-github2`.
